services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
  database:
    build:
      dockerfile: docker/database/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: dk234@1sa&*ca98
      MARIADB_DATABASE: 234kja#$)(an@!@#045
      MARIADB_USER: user
      MARIADB_PASSWORD: dk234@1sa&*ca98
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
    driver: local
