<?php
use Zend\Mvc\Application;
?>
<h1><?= $this->translate('A 404 error occurred', 'application') ?></h1>
<h2><?= $this->message ?></h2>

<?php if (! empty($this->reason)) :
    switch ($this->reason) {
        case Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
            $reasonMessage = $this->translate(
                'The requested controller was unable to dispatch the request.',
                'application'
            );
            break;
        case Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH:
            $reasonMessage = $this->translate(
                'The requested middleware was unable to dispatch the request.',
                'application'
            );
            break;
        case Application::ERROR_CONTROLLER_NOT_FOUND:
            $reasonMessage = $this->translate(
                'The requested controller could not be mapped to an existing controller class.',
                'application'
            );
            break;
        case Application::ERROR_CONTROLLER_INVALID:
            $reasonMessage = $this->translate(
                'The requested controller was not dispatchable.'
            );
            break;
        case Application::ERROR_ROUTER_NO_MATCH:
            $reasonMessage = $this->translate(
                'The requested URL could not be matched by routing.',
                'application'
            );
            break;
        default:
            $reasonMessage = $this->translate(
                'We cannot determine at this time why a 404 was generated.',
                'application'
            );
            break;
    }
?>
<p><?= $reasonMessage ?></p>
<?php endif ?>

<?php if (! empty($this->controller)) : ?>
<dl>
    <dt><?= $this->translate('Controller', 'application')?>:</dt>
    <dd>
        <?= $this->escapeHtml($this->controller) ?>
        <?php
        if (! empty($this->controller_class) && $this->controller_class != $this->controller) {
            printf($this->translate('resolves to %s', 'application'), $this->escapeHtml($this->controller_class));
        }
        ?>
    </dd>
</dl>
<?php endif ?>

<?php if (! empty($this->display_exceptions)) : ?>
    <?php if (isset($this->exception)
        && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
<hr/>

<h2><?= $this->translate('Additional information', 'application')?>:</h2>
<h3><?= get_class($this->exception) ?></h3>
<dl>
    <dt><?= $this->translate('File', 'application')?>:</dt>
    <dd>
        <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
    </dd>
    <dt><?= $this->translate('Message', 'application')?>:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
    </dd>
    <dt><?= $this->translate('Stack trace', 'application')?>:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
    </dd>
</dl>

        <?php if ($ex = $this->exception->getPrevious()) : ?>
<hr/>

<h2><?= $this->translate('Previous exceptions', 'application')?>:</h2>
<ul class="list-unstyled">
            <?php $icount = 0 ?>
            <?php while ($ex) : ?>
    <li>
        <h3><?= get_class($ex) ?></h3>
        <dl>
            <dt><?= $this->translate('File', 'application')?>:</dt>
            <dd>
                <pre><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
            </dd>
            <dt><?= $this->translate('Message', 'application')?>:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getMessage()) ?></pre>
            </dd>
            <dt><?= $this->translate('Stack trace', 'application')?>:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
            </dd>
        </dl>
    </li>
                <?php
                $ex = $ex->getPrevious();
                if (++$icount >= 50) {
                    echo '<li>'. $this->translate(
                        'There may be more exceptions,
                        but we do not have enough memory to process it.',
                        'application'
                    ) . '</li>';
                    break;
                }
                ?>
            <?php endwhile ?>
</ul>
        <?php endif ?>
    <?php else : ?>
<h3><?= $this->translate('No Exception available', 'application')?></h3>
    <?php endif ?>
<?php endif ?>
