<html>
    <?php 
        $this->doctype(Laminas\View\Helper\Doctype::HTML5);
        $this->inlineScript()->prependFile('/' . $this->asset('js/scripts.js'));
        $this->headMeta()
            ->appendHttpEquiv('Content-Type', 'text/html')
            ->appendHttpEquiv('Content-Language', 'en-US')
            ->appendHttpEquiv('pragma', 'no-cache')
            ->appendHttpEquiv('Cache-Control', 'no-cache');
        $this->headMeta()->setCharset('UTF-8');
        echo $this->headMeta();

        echo $this->headTitle('Vetopedia')->setSeparator(' - ');

        // Setting links
        $this->headLink(['rel' => 'icon', 'href' => '/img/vetopedia_logo.svg'], 'PREPEND')
            ->setStylesheet('/'.$this->asset("css/styles.css"));
        // Rendering the links from the layout;
        echo $this->headLink();
    ?>

    <body>
        <header class="page-header" role="banner">
            <h1 class="title">Vetopedia</h1><img src="/img/vetopedia_logo.svg" alt = "vetopedia logo" width="30em">
            <nav>
                <ul class="nav">
                    <li><a href="/start">Get Started</a></li>
                    <li><a href="/docs">Documentation</a></li>
                    <li><a href="/about">About Us</a></li>
                    <li><a href="/donate">Donate</a></li>
                </ul>
            </nav>
        </header>
 
        <?= $this->content; ?>

        <footer>
            Vetopedia @ 2024, All <a href="/home">rights</a> reserved.
        </footer>

    <?= $this->inlineScript(); ?>
    </body>
</html>
