<p>
    This is the homepage
</p>
<pre><code>&lt;p&gt;Sample text here...&lt;/p&gt;
&lt;p&gt;And another line of sample text here...&lt;/p&gt;
<var>y</var> = <var>m</var><var>x</var> + <var>b</var>
To switch directories, type <kbd>cd</kbd> followed by the name of the directory.<br>
To edit settings, press <kbd><kbd>ctrl</kbd> + <kbd>,</kbd></kbd>
</code></pre>
<samp>This text is meant to be treated as sample output from a computer program.</samp>
