<main>
    <div>Acquire Hidden Academic Skills</div>
    <small>That are not Always teached in classrooms</small>
    <div>Choose where you want to get Started</div>
    <section>
        <header>
                <h1>R Coding</h1>
        </header>
            <p>
                Dolore magna quis laborum ipsum fugiat amet laboris. Esse ipsum magna fugiat consequat ex Lorem proident ea. Do ullamco Lorem commodo ullamco esse eu. Eu sit quis ex excepteur. Sunt laboris ex anim in eiusmod excepteur qui proident non aute velit irure anim nostrud. In nulla sunt anim ullamco qui do dolor velit ea commodo do duis fugiat nostrud. Voluptate proident exercitation voluptate ut reprehenderit proident enim quis.
            </p>
    </section>
    <section>
        <header>
            <h1>Python for Datascience</h1>
        </header>
            Sunt ea Lorem elit amet irure Lorem exercitation anim cupidatat ea commodo nisi proident. Laborum nisi fugiat voluptate ad ex commodo fugiat reprehenderit amet dolor proident cupidatat duis irure. Id labore veniam pariatur ullamco. Dolor irure ut elit velit consectetur. Veniam nostrud et magna ullamco culpa adipisicing et aliquip incididunt velit enim.
    </section>
    <section>
        <header>
                <h1>QGIS for Academic maps</h1>
        </header>
            <p>
                Eu aliqua deserunt sit elit est duis eu qui. Est id nisi nulla non. Esse pariatur mollit in nostrud ad elit proident dolor ut mollit sunt fugiat. Enim cupidatat dolor anim magna do non amet amet ut occaecat mollit quis magna exercitation. Sunt do dolore reprehenderit nulla est. Aliqua ipsum proident aliqua duis consectetur est excepteur voluptate.
            </p>
    </section>
    <section>
        <header>
            <h1>Latex Document formatting</h1>
        </header>
            <p>
                Nostrud laboris in dolore anim sit consectetur. Mollit qui velit aliquip ea Lorem officia ea do do sint. Qui aute officia nostrud laboris sunt.
            </p>
    </section>
</main>
